name: Mindless Rambling Nonsense
markdown: kramdown
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
highlighter: rouge
description: My thoughts are mindless and rambling so the best place for them is the internet
encoding: UTF-8
url: http://pauldambra.github.io
author: paul.dambra+fb-instant@gmail.com
plusProfile: https://plus.google.com/114260096260757534167?rel=author
excerpt_separator: <!--more-->
exclude: ['Guardfile', .gitgnore', '.ruby-version', 'build.sh', 'Gemfile', 'Gemfile.lock', 'README.md']
ampdir: amp
facebook_id: 1029758320473951
amp_googleanalytics_id: UA-49969634-2
future: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      header_class: "hero"
gems:
  - octopress-paginate
  - octopress-minify-html
exclude:
  - node_modules
  - sw-config.js
  - "*.sh"
  - htmltest.rb
  - package.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - README.md
